global using System.Runtime.InteropServices;
global using System.Text;
global using static MpvLib.Native.LibMpv;
global using MpvLib.Data;
global using MpvLib.Native;
global using System.Globalization;
global using MpvLib.Utils;
global using System.Text.RegularExpressions;
global using System.Runtime.Versioning;
global using Core.Logger;
